name: Deploy Zola site to GitHub Pages

on:
  push:
    branches:
      - main  # Change this if your default branch is different

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Install Snap
        run: |
          sudo apt update
          sudo apt install -y snapd
          sudo snap install zola --edge

      - name: Build site
        run: zola build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
